namespace Volt;

/// <summary>Byte fragment rendered by an island action, backed by a pooled buffer.</summary>
public sealed class VoltFragment : IDisposable
{
    private readonly PooledBufferWriter _buffer = new();
    private HtmlWriter? _writer;

    public ReadOnlySpan<byte> Html => _buffer.WrittenSpan;

    /// <summary>A pooled writer over the fragment buffer (no hydration script inside fragments).</summary>
    public HtmlWriter Writer => _writer ??= HtmlWriter.Rent(_buffer, includeHydrationScript: false);

    public void Dispose()
    {
        _writer?.Return();
        _writer = null;
        _buffer.Dispose();
    }
}

/// <summary>Dispatches an island action: (stateJson, action, argsJson) → newStateJson.</summary>
public delegate byte[] IslandDispatch(ReadOnlySpan<byte> stateJson, string action, ReadOnlySpan<byte> argsJson);

/// <summary>Renders the complete replacement markup (form + island) for an action response.</summary>
public delegate VoltFragment IslandRenderFragment(ReadOnlySpan<byte> stateJson, string sid, string? token);

/// <summary>Registry entry for one island type, generated by the Volt source generator.</summary>
public sealed class VoltIslandEntry
{
    public required string Name { get; init; }
    public required IslandDispatch Dispatch { get; init; }
    public required IslandRenderFragment Render { get; init; }
}

/// <summary>Island table filled at startup by generated code; looked up by island name.</summary>
public sealed class VoltIslandRegistry
{
    public static VoltIslandRegistry Root { get; } = new();

    private readonly Dictionary<string, VoltIslandEntry> _entries = new(StringComparer.Ordinal);
    private readonly object _lock = new();
    private Dictionary<string, VoltIslandEntry>? _frozen;

    public void Register(VoltIslandEntry entry)
    {
        lock (_lock)
        {
            if (_entries.ContainsKey(entry.Name))
                throw new InvalidOperationException($"Volt: duplicate island '{entry.Name}'.");
            _entries.Add(entry.Name, entry);
            _frozen = null;
        }
    }

    public VoltIslandEntry? Find(string name)
    {
        var frozen = _frozen;
        if (frozen is null)
        {
            lock (_lock)
            {
                _frozen = new Dictionary<string, VoltIslandEntry>(_entries, StringComparer.Ordinal);
                frozen = _frozen;
            }
        }
        return frozen.TryGetValue(name, out var entry) ? entry : null;
    }
}
