<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
    <RootNamespace>Volt</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <PackageId>Volt.Core</PackageId>
    <Description>Volt.NET runtime: zero-allocation HTML rendering, SSG/SSR/ISR engine, routing, islands, SEO, hydration runtime.</Description>
  </PropertyGroup>
</Project>
